# version: "3.9"

services:
  reranker:
    build: ./crossencoder
    container_name: reranker
    ports:
      - "8000:8000"

  retriever:
    build: ./retriever
    container_name: retriever
    ports:
      - "8001:8001"
    environment:
      RERANKER_URL: "http://reranker:8000"
    depends_on:
      - reranker